### ISSUE TITLE
Update react/http to v1

### ISSUE THREAD

**Issue by WyriHaximus** [WyriHaximus/reactphp-http-middleware-compress-assets#16]
This package needs update to react/http v1 and have a new major release tag.

Check list for that:

1. Update the dependency
2. Update the code based on migration guide: https://github.com/reactphp/http/releases/tag/v1.0.0
3. Make sure tests don't fail, not that this project hasn't been update in a while so if some jobs or Travis fail that is fine
4. Create PR

**Comment by makeey** [comment]
@WyriHaximus Hello, I assume nobody wasn't working on the issue so far so I took it, I've updated dependency (react/http) up to v1.0.0. I had to change the namespace in import for Response and ServerRequest. If you found something else please let me know ;)

**Comment by WyriHaximus** [comment]
@makeey Not that I'm aware of, and otherwise I'd assume they put it here. Put this up as easy Hacktobefest issue to PR, and pretty happy to see you pick it up 👍 . Thank you for that
